name: CI for Playwright tests

on:
  push:
    branches: [ "default" ]
  pull_request:
    branches: [ "default" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Build project and install dependencies
        run: mvn clean install -pl core -DskipTests -am

      - name: Restore Allure History
        run: |
          mkdir -p ui-playwright/allure-history
          mvn antrun:run@restore-allure-history -pl ui-playwright
        continue-on-error: true

      - name: Run tests for ui-playwright module
        run: mvn clean test -pl ui-playwright -Denv=qa

      - name: Generate Allure Environment Properties
        if: always()
        run: |
          mkdir -p ui-playwright/target/allure-results
          echo "Environment=QA" >> ui-playwright/target/allure-results/environment.properties
          echo "Framework=Playwright" >> ui-playwright/target/allure-results/environment.properties
          echo "Branch=${{ github.ref_name }}" >> ui-playwright/target/allure-results/environment.properties
          echo "OS=${{ runner.os }}" >> ui-playwright/target/allure-results/environment.properties

      - name: Generate Allure Report
        if: always()
        run: mvn allure:report -pl ui-playwright

      - name: Save Allure History
        if: always()
        run: mvn antrun:run@copy-allure-history -pl ui-playwright

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-playwright
          path: ui-playwright/target/site/allure-maven-plugin/
          retention-days: 30

      - name: Publish Allure Report to GitHub Pages
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: ui-playwright/target/allure-results
          allure_report: ui-playwright/target/allure-report
          gh_pages: gh-pages
          keep_reports: 10

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ui-playwright/target/allure-report

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4